
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Edits a photo using a text prompt.
 * @param base64Image The base64 encoded image string.
 * @param mimeType The MIME type of the image.
 * @param prompt The text prompt describing the desired edit.
 * @returns A promise that resolves to the base64 string of the edited image.
 */
export const editPhoto = async (base64Image: string, mimeType: string, prompt: string): Promise<string> => {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64Image,
                        mimeType: mimeType,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const firstPart = response.candidates?.[0]?.content?.parts?.[0];
    if (firstPart && firstPart.inlineData) {
        return firstPart.inlineData.data;
    }

    throw new Error("No image was generated by the API.");
};

/**
 * Describes the architecture within a photo.
 * @param base64Image The base64 encoded image string.
 * @param mimeType The MIME type of the image.
 * @returns A promise that resolves to a string containing the description.
 */
export const describePhoto = async (base64Image: string, mimeType: string): Promise<string> => {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: base64Image,
                        mimeType: mimeType,
                    },
                },
                {
                    text: 'Provide a detailed description of the architecture and structural elements visible in this image. Focus on style, materials, and form.',
                },
            ],
        },
    });

    return response.text;
};
